### ISSUE TITLE
Azure Deployment fails on DockerExtension

### ISSUE THREAD

**Issue by skanjo** [sequenceiq/azure-cbd-quickstart#7]
Recently decided to try Cloudbreak on Azure and used the provided template. The installation fails with the following error. All the resources were created but after logging into the server I did not found an installation of Cloudbreak. I assume the setup process failed at the following point and prevents installation of Cloudbreak. Is there a workaround for this?

```
OPERATION ID0B273484C99435C9
TRACKING ID4cab9671-0f34-4306-bb49-68995a6b9782
STATUSConflict
PROVISIONING STATEFailed
TIMESTAMPFri Jul 29 2016 17:48:41 GMT-0500 (CDT)
DURATIONPT3M17.2898861S
TYPEMicrosoft.Compute/virtualMachines/extensions
RESOURCE ID/subscriptions/fdedb26c-9b14-4c81-a422-2372df5d16e8/resourceGroups/dev-cloudbreak/providers/Microsoft.Compute/virtualMachines/cbdeployerVM/extensions/DockerExtension
STATUSMESSAGE{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'DockerExtension'. Error message: \"Enable Docker failed: ERROR: executing systemctl [restart docker] failed: exit status 1\"."
      }
    ]
  }
}
RESOURCEcbdeployerVM/DockerExtension

```

**Comment by mhmxs** [comment]
Hi @skanjo,

Sorry for the late answer (i'm picking up issues organization wide on github). I hope the issue gone already, is it true?

**Comment by skanjo** [comment]
Yes somebody at Hortonworks contacted the team responsible and the issue was fixed. In the end I was able to install on Azure. Thanks!
